### ISSUE TITLE
Invalid file path

### ISSUE THREAD

**Issue by WeicongLee** [SNNafi/media_store_plus#10]
When my file name has special characters such as %, Invalid file path will appear

```java
final bool status = await mediaStore.saveFile(
          tempFilePath: tempFile.path,
          dirType: DirType.download,
          dirName: DirType.download.defaults,
          relativePath: fileSavePath);
```

```java
D/DirName (15690): Download
I/StubController(15690): system app validUid:12261, isFriend:false
D/DisplayName banshu-20230706111451%.pdf(15690): null
E/Exception(15690): Invalid file path
E/Exception(15690): java.io.FileNotFoundException: Invalid file path
E/Exception(15690): 	at java.io.FileInputStream.<init>(FileInputStream.java:155)
E/Exception(15690): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.createOrUpdateFile(MediaStorePlusPlugin.kt:285)
E/Exception(15690): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.saveFile(MediaStorePlusPlugin.kt:181)
E/Exception(15690): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.onMethodCall(MediaStorePlusPlugin.kt:66)
E/Exception(15690): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/Exception(15690): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/Exception(15690): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/Exception(15690): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/Exception(15690): 	at android.os.Handler.handleCallback(Handler.java:900)
E/Exception(15690): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/Exception(15690): 	at android.os.Looper.loop(Looper.java:219)
E/Exception(15690): 	at android.app.ActivityThread.main(ActivityThread.java:8673)
E/Exception(15690): 	at java.lang.reflect.Method.invoke(Native Method)
E/Exception(15690): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/Exception(15690): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

Then a file with a size of 0 B will appear
![1688613966303](https://github.com/SNNafi/media_store_plus/assets/25769324/199895fb-34e8-4c84-94ee-4ca9bae19ff2)

**Comment by SNNafi** [comment]
Fixed. Will available with the next release.

**Comment by WeicongLee** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by SNNafi** [comment]
Released
