### ISSUE TITLE
saveFile fails when path contains spaces

### ISSUE THREAD

**Issue by Fifut** [SNNafi/media_store_plus#2]
Hello.

saveFile fails when path contains spaces:

```
MediaStore.appFolder = "Beep & Speech";

await mediaStorePlugin.saveFile(
        tempFilePath: '/data/user/0/fr.hyperburst.beepandspeech/app_flutter/beep_and_speech_data/Sound one.wav',
        dirType: DirType.audio,
        dirName: DirName.notifications
);
```

Return:
```
E/Exception(26239): java.lang.NullPointerException
E/Exception(26239): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.createOrUpdateFile(MediaStorePlusPlugin.kt:251)
E/Exception(26239): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.saveFile(MediaStorePlusPlugin.kt:182)
E/Exception(26239): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.onMethodCall(MediaStorePlusPlugin.kt:67)
E/Exception(26239): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/Exception(26239): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/Exception(26239): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/Exception(26239): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/Exception(26239): 	at android.os.Handler.handleCallback(Handler.java:938)
E/Exception(26239): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Exception(26239): 	at android.os.Looper.loop(Looper.java:246)
E/Exception(26239): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/Exception(26239): 	at java.lang.reflect.Method.invoke(Native Method)
E/Exception(26239): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/Exception(26239): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

If I replace spaces with _, everything works fine. :
`'/data/user/0/fr.hyperburst.beepandspeech/app_flutter/beep_and_speech_data/Sound_one.wav'`

**Comment by SNNafi** [comment]
Thanks for pointing out this bug. Will fix in the next release.

**Comment by SNNafi** [comment]
Thanks for pointing out this bug. Will fix in the next release.

**Comment by SNNafi** [comment]
@Fifut can you please check now? Just have published __0.0.3__.

**Comment by Fifut** [comment]
It seems to be good.
But I just discovered that I have the same problem with letters with accents. :confused:
But not realy the same

```
E/Exception(14702): MIME type application/octet-stream cannot be inserted into content://media/external_primary/audio/media; expected MIME type under audio/*
E/Exception(14702): java.lang.IllegalArgumentException: MIME type application/octet-stream cannot be inserted into content://media/external_primary/audio/media; expected MIME type under audio/*
E/Exception(14702): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
E/Exception(14702): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
E/Exception(14702): 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
E/Exception(14702): 	at android.content.ContentResolver.insert(ContentResolver.java:2159)
E/Exception(14702): 	at android.content.ContentResolver.insert(ContentResolver.java:2121)
E/Exception(14702): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.createOrUpdateFile(MediaStorePlusPlugin.kt:292)
E/Exception(14702): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.saveFile(MediaStorePlusPlugin.kt:182)
E/Exception(14702): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.onMethodCall(MediaStorePlusPlugin.kt:67)
E/Exception(14702): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/Exception(14702): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/Exception(14702): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/Exception(14702): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/Exception(14702): 	at android.os.Handler.handleCallback(Handler.java:938)
E/Exception(14702): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Exception(14702): 	at android.os.Looper.loop(Looper.java:246)
E/Exception(14702): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/Exception(14702): 	at java.lang.reflect.Method.invoke(Native Method)
E/Exception(14702): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/Exception(14702): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by SNNafi** [comment]
@Fifut can you please check now? Just have published 0.0.4. It should now handle any type of files or file names

**Comment by Fifut** [comment]
Yes, It works perfectly now.
Thank you! 👍

**Comment by SNNafi** [comment]
You are most welcome.
