### ISSUE TITLE
MediaStorePlugin.saveFile error with API 28

### ISSUE THREAD

**Issue by Fifut** [SNNafi/media_store_plus#3]
Hello again 😃 

Wtih API 28 I got this error if  _MediaStore.appFolder_ does not exist when calling _mediaStorePlugin.saveFile_.
In my case _MediaStore.appFolder_ is 'Beep & Speech'

```
E/flutter (11402): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot copy file to '/storage/emulated/0/Notifications/Beep & Speech/Toto.wav', path = '/data/user/0/fr.hyperburst.beepandspeech.beep_and_speech/app_flutter/beep_and_speech_data/Toto.wav' (OS Error: No such file or directory, errno = 2)
E/flutter (11402): #0      _File.copy.<anonymous closure> (dart:io/file_impl.dart:328:9)
E/flutter (11402): <asynchronous suspension>
E/flutter (11402): #1      MediaStore.saveFile (package:media_store_plus/media_store_plus.dart:82:19)
E/flutter (11402): <asynchronous suspension>
```

```
await mediaStorePlugin.saveFile(
        tempFilePath: notificationFile.path,
        dirType: DirType.audio,
        dirName: DirName.notifications)
```

**Comment by Fifut** [comment]
Temporarily fixed by creating the directory before copying.
```
...
      Directory directory = Directory(dirType.fullPath(
          relativePath: relativePath.orAppFolder, dirName: dirName));
      String fileName = Uri.parse(tempFilePath).pathSegments.last.trim();
      File tempFile = File(tempFilePath);

      await Directory(directory.path).create();

      File file = await tempFile.copy(directory.path + "/" + fileName);
      return await file.exists();
...
```

**Comment by SNNafi** [comment]
Nice catch. So, basically, we just need to create the directory in lower APIs as we are using direct _File_ API to do the things.

**Comment by SNNafi** [comment]
Tested in API levels 27 & 28. Thanks for this find out.
![photo_2023-01-24 01 42 09](https://user-images.githubusercontent.com/22527366/214134254-8298c5f1-429b-4e3f-b155-617660f55d9a.jpeg)

![photo_2023-01-24 01 44 23](https://user-images.githubusercontent.com/22527366/214134651-00fca543-ca32-4b71-8d4e-6741145c9001.jpeg)
